### PR TITLE
Fix CMake component find for shared

### LINKED ISSUE #26: CMake config file has issues when using the gflags namespace
### Comment:

The installed CMake config files have a few minor errors that prevent CMake from finding things correctly. I have a patch I will push in a PR that fixes this, where https://github.com/gflags/gflags/commit/0b7f8db2c6b1b0b2451da0923a9ab09cc610e8d1 and https://github.com/gflags/gflags/commit/00fcadd9b89b19c974098f8ad52716234f1cbb27 from quite some time ago resolve the issue where 
```
set(GFLAGS_USE_TARGET_NAMESPACE TRUE)
find_package(gflags REQUIRED COMPONENTS shared)
```
This results in an error without the patch and succeeds with the patched config file.

### PR DESCRIPTION
**Pull request by cryos**
This fixes #26 by patching the config file generated to properly support the namespace and finding the component. The patch is integrated upstream (and has been for many years) as pointed out in the issue with a fuller example.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cryos** [comment]
@conda-forge-admin, please rerender

**Comment by cryos** [comment]
@conda-forge-admin, please rerender

**Comment by cryos** [comment]
I think this is ready for review, really it is just the CMake config patch, but as this package hasn't been built in a while there were many other automated changes that needed to be applied.

**Comment by cryos** [comment]
Any concerns on the patch? This was integrated upstream five years ago as I detailed in #26 and it fixes finding the package correctly when using the namespace. Nothing critical but a useful fix for consumers of the library using CMake and modern namespaced imported targets.

**Comment by xhochy** [comment]
The patch looks fine but could you please use the upstream commits, e.g. https://github.com/gflags/gflags/commit/0b7f8db2c6b1b0b2451da0923a9ab09cc610e8d1.patch, to add the correct attribution to the patches.

**Comment by cryos** [comment]
> The patch looks fine but could you please use the upstream commits, e.g. https://github.com/gflags/gflags/commit/0b7f8db2c6b1b0b2451da0923a9ab09cc610e8d1.patch, to add the correct attribution to the patches.

Good point, I actually patched this without knowing, and then a colleague pointed out the matching commits... I will update my PR later today to make that clearer.

**Comment by cryos** [comment]
Assuming it all rebuilds as expected I think this addresses your request @xhochy.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
