### PR TITLE
Include libgflags.so.2 library files on Linux

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by isuruf** [comment]
I don't think this is a good idea. They intentionally changed the SOVERSION because the ABI was broken. Packages needing this should be built with the newer version or have a constraint for the older version

**Comment by advance512** [comment]
If you're installing caffe via conda and running into this, try:
```
conda install python=2.7 caffe-gpu protobuf gflags
```

**Comment by mariusvniekerk** [comment]
close due to staleness

**Pull request closed without merging**
